version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore VoodooApp.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output VoodooApp.sln
  artifacts:
    files:
      - CodeBuild-VoodooApp/build_output/**/*
      - scripts/**/*
